Vizzuality/i2i

- app/assets/stylesheets/_base.scss
- app/views/layouts/application.html.erb
- app/views/layouts/static_pages.html.erb
Sara told me the header has to have fullscreen width so there's no point on keeping the current app container.
> Removed app width container

- app/assets/javascripts/application.js
- app/assets/javascripts/components/shared/modal.js
- app/assets/javascripts/components/shared/modals/modal-team.js
- app/assets/javascripts/helpers/accessibility.js
- app/assets/javascripts/pages/static_pages/about.js
- app/assets/javascripts/static_pages.js
- app/assets/javascripts/templates/shared/modal.jst.ejs
- app/views/static_pages/about.html.erb
This PR makes the modal component accessible:
- it makes it correctly interpreted by screen readers
- it makes the focus behave as expected
- it makes the team modal actionable by the keyboard
> Makes the modal component accessible

- app/assets/stylesheets/components/shared/c-card.scss
- app/views/libraries/index.html.erb
- app/views/news/index.html.erb
This PR replaces all images in cards into backgrounds.
> Makes backgrounds great again

- app/assets/stylesheets/_base.scss
- app/assets/stylesheets/_helpers.scss
- app/assets/stylesheets/components/data-portal/c-tag.scss
- app/assets/stylesheets/components/data-portal/c-widget.scss
- app/assets/stylesheets/components/shared/c-select.scss
- app/assets/stylesheets/components/shared/c-switcher.scss
- app/assets/stylesheets/layouts/l-country.scss
- app/views/data_portal/countries/show.html.erb
- app/views/shared/_header.html.erb
Pivotal task: https://www.pivotaltracker.com/story/show/139808073
TO-DO:
> data portal country page

- app/assets/stylesheets/components/shared/c-contribute-section.scss
- app/views/community/index.html.erb
- app/views/data_portal/index.html.erb
- app/views/homepage/index.html.erb
- app/views/libraries/index.html.erb
- app/views/shared/_contribute.html.erb
- app/views/static_pages/about.html.erb
- app/views/updates/index.html.erb
Here I added some text the client sent to replace the lorem ipsum from section banners and Home page.
> copys from the client

- app/helpers/application_helper.rb
- app/views/community/index.html.erb
- app/views/data_portal/index.html.erb
- app/views/data_portal/show.html.erb
- app/views/homepage/index.html.erb
- app/views/layouts/application.html.erb
- app/views/layouts/data_portal.erb
- app/views/libraries/index.html.erb
- app/views/static_pages/about.html.erb
- app/views/updates/blogs/index.html.erb
- app/views/updates/blogs/show.html.erb
- app/views/updates/events/index.html.erb
- app/views/updates/events/show.html.erb
- app/views/updates/index.html.erb
- app/views/updates/news/index.html.erb
- app/views/updates/news/show.html.erb
The country page (inside data portal section) has no title until we find out a way to provide the name country name coming from API.
> Added dynamic page titles

- app/views/homepage/index.html.erb
https://basecamp.com/1756858/projects/12871501/messages/67104560
> home page texts

- app/helpers/date_helper.rb
- app/views/data_portal/index.html.erb
- app/views/libraries/index.html.erb
- app/views/updates/blogs/index.html.erb
- app/views/updates/blogs/show.html.erb
- app/views/updates/events/index.html.erb
- app/views/updates/events/show.html.erb
- app/views/updates/index.html.erb
- app/views/updates/news/index.html.erb
- app/views/updates/news/show.html.erb
Pivotal task: https://www.pivotaltracker.com/story/show/141116769
This PR makes dates in cards more readable having a beautiful format.
> Beautifies dates in cards

- app/assets/stylesheets/components/updates/c-article.scss
- app/views/updates/events/show.html.erb
Pivotal task: https://www.pivotaltracker.com/story/show/141117219
This PR adds a link to event detail page that allows the user to see more details about the event in the event site.
Also, this PR is based on  https://github.com/Vizzuality/i2i/pull/63 work, so please, wait for it to merge.
> Adds external event link

- app/views/updates/blogs/show.html.erb
- app/views/updates/events/show.html.erb
- app/views/updates/news/show.html.erb
Close https://www.pivotaltracker.com/story/show/140474825 after merge, please.
> Added author to detail pages in front

- app/assets/stylesheets/components/shared/c-card.scss
- app/assets/stylesheets/layouts/l-news.scss
- app/views/community/index.html.erb
- app/views/data_portal/index.html.erb
- app/views/updates/blogs/index.html.erb
- app/views/updates/blogs/show.html.erb
- app/views/updates/events/index.html.erb
- app/views/updates/events/show.html.erb
- app/views/updates/index.html.erb
- app/views/updates/news/index.html.erb
- app/views/updates/news/show.html.erb
This PR adds the asked changes in point 2 here https://github.com/Vizzuality/i2i/pull/67#pullrequestreview-26015948
If you find it OK, merge with `feature/community-page` and also merge `feature/community-page` if it is ready.
> Links wraps whole card content

- app/assets/stylesheets/components/shared/c-spinning-loader.scss
Pivotal task: https://www.pivotaltracker.com/story/show/141581219
> Reduces spinner size

- app/views/updates/news/show.html.erb
Pivotal task: https://www.pivotaltracker.com/story/show/141581937
> Adds HTML conversion to news content

- app/admin/admin_user.rb
- app/admin/member.rb
- app/enumerations/role_type.rb
- app/models/member.rb
- db/migrate/20170314165753_create_members.rb
- test/fixtures/members.yml
- test/models/member_test.rb
Added the members management to the backoffice
> Added Members to the backoffice

- app/assets/javascripts/templates/data_portal/widgets/analysis.jst.ejs
This PR redesigns the chart used for the analysis.
> Redesign the chart for the analysis

- app/assets/javascripts/pages/static_pages/library.js
- app/assets/javascripts/pages/static_pages/updates/events.js
- app/assets/javascripts/routers/application.js
- app/assets/stylesheets/layouts/l-keep-updated.scss
- app/helpers/date_helper.rb
- app/views/updates/events/index.html.erb
Pivotal task: https://www.pivotaltracker.com/story/show/141116819
This PR adds a chronological way to organize events.
> Adds chronological filters to events page

- app/admin/library.rb
- app/models/library.rb
- db/migrate/20170404115028_remove_content_from_libraries.rb
- db/schema.rb
I tested it and it's all fine. Please check if it's all that you need.
> Removed content from library

- app/assets/javascripts/components/data_portal/modals/modal-save-widget.js
- app/assets/javascripts/components/data_portal/slide.js
- app/assets/javascripts/components/shared/modal.js
- app/assets/javascripts/templates/data_portal/chart-widget.jst.ejs
- app/assets/javascripts/templates/data_portal/modals/modal-save-widget.jst.ejs
- app/assets/javascripts/templates/data_portal/slides/shareWidget.jst.ejs
- app/assets/javascripts/views/data_portal/ChartWidgetView.js
- app/assets/javascripts/views/data_portal/slides/ShareView.js
- app/assets/stylesheets/_base.scss
- app/assets/stylesheets/_settings.scss
- app/assets/stylesheets/components/data-portal/c-modal-save-widget.scss
- app/assets/stylesheets/components/data-portal/c-share-widget.scss
- app/assets/stylesheets/components/data-portal/c-slider.scss
- app/assets/stylesheets/components/shared/c-button.scss
- app/assets/stylesheets/components/shared/c-modal.scss
Pivotal task: https://www.pivotaltracker.com/story/show/141225215
Modal buttons distribution are pending on design (https://www.pivotaltracker.com/story/show/143021909)
NOTES:
- `print` function depends on the embed widget (the plan is to take a screenshot of this)
- `download` function will be developed later because of complexity.
-  Inside `share`, we will need to provide a real URL for share the widget and embed one.
These points are writte down in Pivotal: https://www.pivotaltracker.com/story/show/143164293
> Save widget

- app/assets/javascripts/components/data_portal/modals/modal-download-all.js.erb
- app/assets/stylesheets/components/shared/c-button.scss
This PR involves this task: https://www.pivotaltracker.com/story/show/143562591
> minor-styles-fixes

- app/assets/javascripts/collections/data_portal/IndicatorsCollection.js
- app/assets/javascripts/pages/data_portal/DataPortalCountryPage.js
- app/assets/javascripts/pages/data_portal/DataPortalIndicatorPage.js
Pivotal task: https://www.pivotaltracker.com/story/show/143487973
This PR adds to the collection:
- default sorting
- `getVisibleIndicators` method
> Adds some improves to indicator collection

- app/assets/javascripts/application.js
- app/assets/javascripts/data_portal.js.erb
- app/views/layouts/application.html.erb
- app/views/layouts/data_portal.erb
- app/views/layouts/embed.erb
- app/views/shared/_analytics.html.erb
This PR adds Google analytics to the app when ran with the production environment.
> Add Google analytics to the layouts

- app/assets/javascripts/components/data_portal/modals/modal-save-widget.js
- app/assets/javascripts/components/data_portal/slide.js
- app/assets/javascripts/views/data_portal/slides/ShareView.js.erb
This PR implements the download button of the widgets.
> Let the user download the expanded data of the widgets

- app/assets/javascripts/components/data_portal/modals/modal-save-widget.js.erb
- app/assets/javascripts/pages/data_portal/DataPortalIndicatorPage.js
- app/assets/javascripts/routers/data_portal.js
- app/assets/javascripts/views/data_portal/ChartWidgetView.js
- app/assets/stylesheets/components/data-portal/c-chart-widget.scss
- app/assets/stylesheets/layouts/l-embed.scss
- app/views/data_portal/indicator/show.html.erb
This PR implement the print button of the save modal.
> Let the user print a widget

- app/assets/javascripts/components/data_portal/modals/modal-save-widget.js.erb
- app/assets/javascripts/pages/data_portal/DataPortalCountryPage.js
- app/assets/javascripts/templates/data_portal/chart-widget.jst.ejs
- app/assets/javascripts/views/data_portal/ChartWidgetView.js
Task: https://www.pivotaltracker.com/story/show/145504153
> Adds save button for table mode

- app/assets/javascripts/components/data_portal/modals/modal-chart-analysis.js
- app/assets/javascripts/components/data_portal/modals/modal-chart-compare.js
- app/assets/javascripts/components/data_portal/modals/modal-save-widget.js.erb
- app/assets/javascripts/components/shared/modal.js
- app/assets/javascripts/components/shared/modals/YoutubeModal.js
- app/assets/javascripts/components/shared/modals/modal-about-read-more.js
- app/assets/javascripts/components/shared/modals/modal-team.js
- app/assets/javascripts/templates/data_portal/filters.jst.ejs
- app/assets/javascripts/templates/data_portal/filters/select-indicators.jst.ejs
- app/assets/javascripts/templates/data_portal/modals/modal-chart-analysis.jst.ejs
- app/assets/javascripts/templates/data_portal/modals/modal-chart-compare.jst.ejs
- app/assets/javascripts/templates/data_portal/modals/modal-chart-selector.jst.ejs
- app/assets/javascripts/templates/shared/modal.jst.ejs
- app/assets/javascripts/templates/shared/modals/modal-newsletter.jst.ejs
- app/assets/javascripts/views/data_portal/FiltersIndicatorsModal.js
- app/assets/javascripts/views/shared/NewsletterModalView.js
- app/assets/stylesheets/_base.scss
- app/assets/stylesheets/_settings.scss
- app/assets/stylesheets/components/about/c-modal-about-read-more.scss
- app/assets/stylesheets/components/data-portal/c-modal-chart-analysis.scss
- app/assets/stylesheets/components/data-portal/c-modal-chart-compare.scss
- app/assets/stylesheets/components/data-portal/c-modal-chart-selector.scss
- app/assets/stylesheets/components/data-portal/c-modal-filters.scss
- app/assets/stylesheets/components/shared/c-button.scss
- app/assets/stylesheets/components/shared/c-modal-newsletter.scss
- app/assets/stylesheets/components/shared/c-modal.scss
Task: https://www.pivotaltracker.com/story/show/145448455
> Responsive modals

- app/admin/member.rb
- app/models/member.rb
- app/serializers/member_serializer.rb
- db/migrate/20170614104525_add_order_to_members.rb
- db/schema.rb
- test/fixtures/members.yml
- test/models/member_test.rb
Add field order to members as an integer for sorting purposes.
> Add orders as integer to members

- app/admin/event.rb
- app/assets/stylesheets/components/updates/c-article.scss
- app/models/event.rb
- app/views/updates/events/show.html.erb
Reverts Vizzuality/i2i#147
CSS problems
> Revert "Feature/event documents"

- app/admin/event.rb
- app/assets/stylesheets/components/updates/c-article.scss
- app/models/event.rb
- app/views/updates/events/show.html.erb
Reverts Vizzuality/i2i#149
CSS bug wasn't coming from this PR
> Revert "Revert "Feature/event documents""

- app/assets/javascripts/components/shared/modals/modal-team.js
- app/assets/javascripts/pages/static_pages/about.js
- app/assets/javascripts/routers/application.js
- app/controllers/static_pages_controller.rb
- app/views/static_pages/about.html.erb
Task: https://www.pivotaltracker.com/story/show/150960652
> About page navigation

- app/assets/stylesheets/components/insights/c-article.scss
Fix text spacing for article list items (e.g. found http://i2ifacility.org/news/delving-into-data-practical-tools-for-fsps).
> Amend article list word spacing to reflect default paragraph typography

- app/assets/javascripts/templates/data_portal/widgets/analysis-mobile.jst.ejs
- app/assets/javascripts/templates/data_portal/widgets/analysis.jst.ejs
- app/assets/javascripts/templates/data_portal/widgets/bar.jst.ejs
- app/assets/javascripts/templates/data_portal/widgets/compare.jst.ejs
- app/assets/javascripts/templates/data_portal/widgets/empty.jst.ejs
- app/assets/javascripts/templates/data_portal/widgets/radial.jst.ejs
- app/assets/javascripts/templates/data_portal/widgets/stacked-bar-mobile.jst.ejs
- app/assets/javascripts/templates/data_portal/widgets/stacked-bar.jst.ejs
Task: https://www.pivotaltracker.com/story/show/151632793
> Changes chart font

- app/controllers/concerns/relatable.rb
- app/views/homepage/index.html.erb
- app/views/initiatives/filter_index.html.erb
- app/views/insights/index.html.erb
- app/views/insights/show.html.erb
- app/views/shared/_cards.html.erb
- app/views/shared/show/_blog.html.erb
- app/views/shared/show/_event.html.erb
- app/views/shared/show/_news.html.erb
Task: https://www.pivotaltracker.com/story/show/151834533
> Related content

- Gemfile
- Gemfile.lock
- config/initializers/cors.rb
A simple implementation of CORS.
Let's deploy it in staging to be sure it's working.
> Added CORS

- app/controllers/fdapi/project_metadata_controller.rb
This is just a quick solution to have the filter working.
This needs deeps refactoring.
> A quick fix to the problem. Needs refactor!

- app/assets/stylesheets/layouts/homepage/twitter-slider.scss
- app/views/homepage/_twitter_slider.html.erb
Proposal for: https://github.com/Vizzuality/i2i/pull/211
This a proposal changing the markup a bit, let me know your opinion and if you find OK to continue working on this. Thanks!
TO-DO:
- Quotes marks should be SVG icons (ask Sara for it). This way we can manage them better and imitate the exact style.
- On mobile: what to do with the navigation arrow? They don't fit in the current design when previous and next ones are available at the same time.
> Alternative markup for tweet

- app/assets/javascripts/pages/data_portal_financial_diaries/DataPortalFinancialDiariesIndexPage.js
- app/views/data_portal_financial_diaries/_no_data_available.html.erb
- app/views/data_portal_financial_diaries/index.html.erb
Task: https://www.pivotaltracker.com/story/show/152204617
> Adds placeholder to chart when data is not available

- app/assets/stylesheets/layouts/homepage/l-featured-insights.scss
- app/views/homepage/index.html.erb
Closes https://www.pivotaltracker.com/story/show/152110871
> Fix card heading spacing on the homepage

- app/views/shared/show/_blog.html.erb
Closes https://www.pivotaltracker.com/story/show/150961572
> Add link from insight author to the about team member modal

- app/assets/stylesheets/layouts/l-library.scss
Closes https://www.pivotaltracker.com/story/show/152234160
> FIx insights submenu to allow scroll on mobile

- app/assets/javascripts/helpers/utils.js
- app/assets/javascripts/pages/data_portal_financial_diaries/DataPortalFinancialDiariesIndexPage.js
- app/assets/javascripts/views/financial_diaries/VegaChartView.js
- app/assets/javascripts/views/financial_diaries/visualisations/GroupedBarView.js
- app/assets/javascripts/views/financial_diaries/visualisations/MainChartView.js
Task: https://www.pivotaltracker.com/story/show/152279977
> Add dynamic chart titles

- app/assets/javascripts/components/data_portal/modals/modal-save-widget.js.erb
Can you please make sure that this modal is only being used for finscope widget download? Thanks
> Hardcode data portal download size

- app/assets/stylesheets/components/shared/c-header.scss
- app/views/data_portal_financial_diaries/index.html.erb
@andresgnlez please confirm if ok to remove templated js?
> Fix navigation for country financial diaries page

- app/assets/stylesheets/layouts/l-data-portal-country.scss
- app/views/data_portal/show.html.erb
Towards https://www.pivotaltracker.com/story/show/152201179
> Fix country profile nav implementation for finscope page

- app/assets/stylesheets/components/shared/c-app-logo.scss
- app/assets/stylesheets/components/shared/c-header.scss
- app/assets/stylesheets/components/shared/c-hero.scss
- app/assets/stylesheets/layouts/homepage/l-twitter.scss
- app/assets/stylesheets/layouts/l-homepage.scss
- app/assets/stylesheets/layouts/shared/l-intro.scss
- app/views/homepage/_cover_slider.html.erb
Closes https://www.pivotaltracker.com/story/show/152234070
> Fix homepage header layout for mobile

- app/assets/stylesheets/components/shared/c-modal-newsletter.scss
- app/assets/stylesheets/components/shared/c-modal.scss
Closes https://www.pivotaltracker.com/story/show/152234107
> Fix newsletter mobile layout

- app/assets/javascripts/views/shared/mobile-menu.js
- app/assets/stylesheets/_helpers.scss
- app/assets/stylesheets/components/shared/c-mobile-menu.scss
Closes https://www.pivotaltracker.com/story/show/152234189
> Fix responsive static menu button and prevent scroll when overlay open

- app/assets/javascripts/components/data_portal_financial_diaries/CustomTooltip.js
- app/assets/javascripts/views/financial_diaries/VegaChartView.js
- app/assets/javascripts/views/financial_diaries/visualisations/MainChartView.js
- app/assets/stylesheets/components/financial-diaries/c-custom-tooltip.scss
- app/views/data_portal_financial_diaries/index.html.erb
Tasks: 
https://www.pivotaltracker.com/story/show/152284051
https://www.pivotaltracker.com/story/show/152319839
> Custom tooltip

- app/controllers/data_portal_financial_diaries_controller.rb
Task: https://www.pivotaltracker.com/story/show/152319817
> Makes income as default indicator

- app/assets/javascripts/pages/data_portal_financial_diaries/DataPortalFinancialDiariesIndexPage.js
- app/assets/javascripts/views/financial_diaries/visualisations/MainChartHouseholdView.js
- app/assets/javascripts/views/financial_diaries/visualisations/MainChartView.js
- app/views/data_portal_financial_diaries/index.html.erb
Task: https://www.pivotaltracker.com/story/show/152342919
> Splits main chart into two different charts

- app/assets/javascripts/pages/data_portal_financial_diaries/DataPortalFinancialDiariesIndexPage.js
Task: https://www.pivotaltracker.com/story/show/152345433
> Fix updating filters

- app/assets/javascripts/pages/data_portal_financial_diaries/DataPortalFinancialDiariesIndexPage.js
- app/assets/javascripts/views/financial_diaries/visualisations/GroupedBarView.js
- app/views/data_portal_financial_diaries/index.html.erb
Task: https://www.pivotaltracker.com/story/show/152319784
> Generates grouped bar charts by category

- app/assets/stylesheets/layouts/l-financial-diaries.scss
- app/views/data_portal_financial_diaries/index.html.erb
Task: https://www.pivotaltracker.com/story/show/152335686
> Adds finscope button

- app/assets/stylesheets/components/financial-diaries/c-submenu.scss
- app/assets/stylesheets/layouts/financial-diaries/l-indicator-menu.scss
- app/views/data_portal_financial_diaries/_filters.html.erb
- app/views/layouts/data_portal_financial_diaries.erb
Task: https://www.pivotaltracker.com/story/show/152351175
> Adds new filter design

- app/views/initiatives/filter_index.html.erb
- app/views/initiatives/show.html.erb
- app/views/insights/show.html.erb
Towards https://www.pivotaltracker.com/story/show/152111071
Closes https://www.pivotaltracker.com/story/show/152278462
> Fix navbars for initiatives and insight pages

- app/assets/stylesheets/components/shared/c-app-logo.scss
- app/assets/stylesheets/components/shared/c-header.scss
- app/assets/stylesheets/layouts/l-tools.scss
Closes https://www.pivotaltracker.com/story/show/152320175
**Todo: test on tablet device**
> Fix menu positioning across viewports

- app/views/homepage/_cover_slider.html.erb
Closes https://www.pivotaltracker.com/story/show/152315813
> Update copy in the homepage cover slider

- app/assets/stylesheets/layouts/l-library.scss
Closes https://www.pivotaltracker.com/story/show/152319983
> Fix content selector to accommodate long text length

- app/assets/stylesheets/components/insights/c-article.scss
- app/views/shared/show/_blog.html.erb
- app/views/shared/show/_event.html.erb
- app/views/shared/show/_news.html.erb
Closes https://www.pivotaltracker.com/story/show/152320127
> Fix article layout and spacing

- app/views/static_pages/about.html.erb
Closes https://www.pivotaltracker.com/story/show/152308269
> Update font sizing for the about page

- app/assets/stylesheets/components/shared/c-footer.scss
- app/views/shared/_footer.html.erb
Closes https://www.pivotaltracker.com/story/show/152288865
> Fix footer header layout

- app/assets/javascripts/components/data_portal_financial_diaries/CountrySelector.js
- app/assets/javascripts/pages/data_portal_financial_diaries/CountryPreview.js
- app/assets/javascripts/pages/data_portal_financial_diaries/DataPortalFinancialDiariesIndexPage.js
- app/assets/javascripts/routers/data_portal_financial_diaries.js
- app/assets/stylesheets/components/shared/c-country-selector.scss
- app/controllers/data_portal_financial_diaries_controller.rb
- app/views/data_portal_financial_diaries/_country-selector.html.erb
- app/views/data_portal_financial_diaries/country_preview.html.erb
- app/views/data_portal_financial_diaries/index.html.erb
Task: https://www.pivotaltracker.com/story/show/152078860
> Adds country selector

- app/assets/javascripts/components/data_portal_financial_diaries/modals/SaveWidgetModal.js
- app/assets/javascripts/components/data_portal_financial_diaries/modals/ShareWidgetModal.js
- app/assets/javascripts/pages/data_portal_financial_diaries/DataPortalFinancialDiariesIndexPage.js
- app/assets/javascripts/routers/data_portal_financial_diaries.js
- app/assets/javascripts/templates/financial_diaries/save_chart.jst.ejs
- app/assets/javascripts/templates/financial_diaries/vega_chart.jst.ejs
- app/assets/javascripts/views/financial_diaries/VegaChartView.js
- app/assets/javascripts/views/financial_diaries/visualisations/GroupedBarView.js
Task: https://www.pivotaltracker.com/story/show/152335857
> Save chart

- app/assets/javascripts/pages/data_portal_financial_diaries/DataPortalFinancialDiariesIndexPage.js
Task: https://www.pivotaltracker.com/story/show/152381470
> Adds household name to chart titles

- app/assets/javascripts/pages/data_portal_financial_diaries/DataPortalFinancialDiariesIndexPage.js
- app/assets/javascripts/specs/main-chart.js
- app/assets/stylesheets/components/financial-diaries/c-submenu.scss
- app/controllers/data_portal_financial_diaries_controller.rb
- app/views/data_portal_financial_diaries/_demographic_filters.html.erb
- app/views/data_portal_financial_diaries/index.html.erb
Part of: https://www.pivotaltracker.com/story/show/152325711
> Adds income filters

- app/views/data_portal/index.html.erb
No task, fix for the observed templating issue:
> Fix data portal country link output

- app/assets/stylesheets/components/about/c-modal-about-read-more.scss
Towards https://www.pivotaltracker.com/story/show/151636869
> Fix list item line heights for about modal

- app/assets/javascripts/templates/data_portal/header.jst.ejs
- app/assets/stylesheets/_helpers.scss
- app/assets/stylesheets/components/data-portal/c-modal-filters.scss
- app/assets/stylesheets/layouts/l-data-portal-country.scss
Towards https://www.pivotaltracker.com/story/show/151636869
> Fix filter modal scroll for FireFox

- app/assets/javascripts/pages/data_portal_financial_diaries/DataPortalFinancialDiariesIndexPage.js
- app/assets/stylesheets/components/financial-diaries/c-demographic-filters.scss
- app/assets/stylesheets/components/shared/c-switcher.scss
- app/assets/stylesheets/layouts/financial-diaries/l-indicator-menu.scss
- app/assets/stylesheets/layouts/shared/l-content-switch.scss
- app/views/data_portal_financial_diaries/_filters_mobile.html.erb
- app/views/data_portal_financial_diaries/_indicators.html.erb
- app/views/data_portal_financial_diaries/_tabs.html.erb
- app/views/data_portal_financial_diaries/index.html.erb
Task: https://www.pivotaltracker.com/story/show/152431274
> Adds new indicators-filters responsive design

- app/assets/javascripts/templates/shared/modals/modal-newsletter.jst.ejs
- app/assets/javascripts/views/shared/NewsletterModalView.js
- app/assets/javascripts/views/shared/newsletter.js
- app/views/shared/_footer.html.erb
Closes https://www.pivotaltracker.com/story/show/152389873
> Add additional newsletter link and update copy

- app/assets/stylesheets/components/financial-diaries/c-no-data-available.scss
- app/views/data_portal_financial_diaries/_no_data_available.html.erb
Closes https://www.pivotaltracker.com/story/show/152344414
> Add no data styling

- app/assets/javascripts/specs/main-chart-mobile.js
- app/assets/javascripts/views/financial_diaries/visualisations/MainChartView.js
- app/assets/stylesheets/components/data-portal/c-widget.scss
- app/views/data_portal_financial_diaries/index.html.erb
Task: https://www.pivotaltracker.com/story/show/152066726
> Add mobile main chart spec

- app/views/data_portal/index.html.erb
- app/views/homepage/index.html.erb
Fixes: https://www.pivotaltracker.com/story/show/152432736
> Fixes data portal numbers

- app/assets/javascripts/components/data_portal_financial_diaries/modals/SaveWidgetModal.js.erb
- app/assets/javascripts/pages/data_portal_financial_diaries/DataPortalFinancialDiariesIndexPage.js
- app/assets/javascripts/views/financial_diaries/VegaChartView.js
- app/assets/javascripts/views/financial_diaries/visualisations/GroupedBarView.js
- app/assets/stylesheets/components/data-portal/c-widget.scss
Task: https://www.pivotaltracker.com/story/show/152504261
> User able to see save option for main chart

- app/assets/javascripts/components/data_portal_financial_diaries/modals/SaveWidgetModal.js.erb
- app/assets/javascripts/components/data_portal_financial_diaries/modals/ShareWidgetModal.js
- app/assets/javascripts/data_portal_financial_diaries_embed.js.erb
- app/assets/javascripts/pages/data_portal_financial_diaries_embed/FinancialDiariesEmbedPage.js
- app/assets/javascripts/routers/data_portal_financial_diaries.js
- app/assets/javascripts/routers/data_portal_financial_diaries_embed.js
- app/assets/stylesheets/components/data-portal/c-modal-save-widget.scss
- app/controllers/data_portal_financial_diaries_controller.rb
- app/controllers/data_portal_financial_diaries_embed_controller.rb
- app/views/data_portal_financial_diaries_embed/index.html.erb
- app/views/layouts/data_portal_financial_diaries_embed.erb
- config/initializers/assets.rb
- config/routes.rb
Task: https://www.pivotaltracker.com/story/show/152439329
> Embed / Print

- app/assets/javascripts/components/shared/socail-nav.js
- app/assets/javascripts/routers/application.js
- app/assets/stylesheets/components/insights/c-social-nav.scss
- app/views/shared/_social-nav.html.erb
- app/views/shared/show/_blog.html.erb
- app/views/shared/show/_event.html.erb
- app/views/shared/show/_news.html.erb
Closes https://www.pivotaltracker.com/story/show/152271828 https://www.pivotaltracker.com/story/show/152504538
> Add social nav to blog and event article pages

- app/views/data_portal_financial_diaries/index.html.erb
Closes https://www.pivotaltracker.com/story/show/152504499
> Fix financial diaries page layout

- app/controllers/data_portal_financial_diaries_controller.rb
- app/views/data_portal_financial_diaries/_indicators.html.erb
- app/views/data_portal_financial_diaries/index.html.erb
https://www.pivotaltracker.com/story/show/152504298
> Sets value indicator, not name

- app/views/data_portal_financial_diaries/_country-selector.html.erb
Closes https://www.pivotaltracker.com/story/show/152504469
> Update data portal country navigation to reflect current page

- app/assets/javascripts/pages/data_portal_financial_diaries/CountryPreview.js
- app/assets/stylesheets/layouts/l-data-portal.scss
- app/assets/stylesheets/layouts/l-preview-country.scss
- app/controllers/data_portal_financial_diaries_controller.rb
- app/views/data_portal_financial_diaries/country_preview.html.erb
https://www.pivotaltracker.com/story/show/152335621
> Add main chart to country preview page

- app/controllers/data_portal_financial_diaries_controller.rb
- app/models/concerns/human_readable.rb
- app/models/household_income_tier.rb
- app/models/member_income_tier.rb
- app/views/data_portal_financial_diaries/_demographic_filters.html.erb
Task: https://www.pivotaltracker.com/story/show/152504154
> Replaces range label

- app/controllers/data_portal_financial_diaries_controller.rb
- app/views/data_portal_financial_diaries/country_preview.html.erb
- app/views/data_portal_financial_diaries/index.html.erb
Fixes https://www.pivotaltracker.com/story/show/152504418
And the corrects text error for https://www.pivotaltracker.com/story/show/151995914
> Update copy for  financial diaries pages

- app/views/data_portal/show.html.erb
- app/views/data_portal_financial_diaries/country_preview.html.erb
Closes https://www.pivotaltracker.com/story/show/152541079
> Fix fixed nav for country preview page

- app/assets/javascripts/pages/data_portal/DataPortalCountryPage.js
- app/assets/javascripts/templates/data_portal/footer.jst.ejs
Part of: https://www.pivotaltracker.com/story/show/152589454
> Hides download for countries without raw data

- app/assets/stylesheets/components/shared/c-card-highlight.scss
- app/assets/stylesheets/layouts/l-about.scss
Closes https://www.pivotaltracker.com/story/show/152551808
> Fix about highlight cards content overflow with large titles

- app/assets/stylesheets/layouts/l-library.scss
- app/views/initiatives/filter_index.html.erb
Part of: https://www.pivotaltracker.com/story/show/152589454
> Adds an option to see all initiatives easily

- app/assets/stylesheets/components/shared/c-modal.scss
Closes https://www.pivotaltracker.com/story/show/152553365
> Fix modal layout sizing across viewports

- app/controllers/insights_controller.rb
- app/views/insights/index.html.erb
Part of: https://www.pivotaltracker.com/story/show/152589454
> Allows see all insights

- app/assets/javascripts/pages/data_portal_financial_diaries/DataPortalFinancialDiariesIndexPage.js
Task: https://www.pivotaltracker.com/story/show/152613821
> Fixes subcategory title

- app/assets/stylesheets/layouts/l-embed.scss
- app/views/data_portal_financial_diaries_embed/index.html.erb
Task: https://www.pivotaltracker.com/story/show/152612498
> Removes vega bindings in print view

- app/assets/javascripts/pages/data_portal_financial_diaries/CountryPreview.js
- app/assets/stylesheets/layouts/l-preview-country.scss
- app/controllers/data_portal_financial_diaries_controller.rb
- app/views/data_portal_financial_diaries/country_preview.html.erb
Task: https://www.pivotaltracker.com/story/show/152612388
> Removes chart from country preview page

- app/assets/javascripts/components/shared/modals/modal-team.js
Closes https://www.pivotaltracker.com/story/show/152555379
> Fix modal error for advisory team members where blogs is undefined

- app/assets/javascripts/templates/shared/modals/modal-team.jst.ejs
- app/assets/stylesheets/components/about/c-modal-profile.scss
Closes https://www.pivotaltracker.com/story/show/152635704
Tested on Safari 11, IE 11, Edge, Firefox, iOS 11 and Chrome 62.
> Fix modal team spacing for firefox and ie

- app/assets/javascripts/components/data_portal/modals/modal-save-widget.js.erb
- app/assets/javascripts/components/data_portal_financial_diaries/modals/SaveWidgetModal.js.erb
- app/assets/javascripts/pages/data_portal/DataPortalCountryPage.js
- app/assets/javascripts/pages/data_portal/DataPortalReportPage.js
Closes https://www.pivotaltracker.com/story/show/152636470
> Update document fragment to support IE

- app/assets/javascripts/components/shared/modal.js
- app/assets/stylesheets/_helpers.scss
Closes https://www.pivotaltracker.com/n/projects/1967391/stories/152633971
~~**TODO:**~~
~~- test modals on `/data-portal`~~
~~- test on IE~~
> Fix modals to maintain position

- app/assets/javascripts/helpers/array-includes-polyfill.js
Closes https://www.pivotaltracker.com/story/show/152806646
@andresgnlez are you happy with this approach, polyfill from
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes
> Fix ie rendering for data portal finscope country page

- app/assets/javascripts/components/shared/fixed-nav.js
- app/assets/stylesheets/layouts/shared/l-intro.scss
Closes https://www.pivotaltracker.com/story/show/152756592
~~**TODO:** Tested on browsers and devices except IE11 and Edge~~
> Fix fixed nav juddering on scroll

- app/views/data_portal/show.html.erb
Closes https://www.pivotaltracker.com/story/show/152752099
> Fix data portal country chart toggle position

- app/assets/stylesheets/components/shared/c-search.scss
- app/assets/stylesheets/layouts/l-library.scss
- app/controllers/searches_controller.rb
- app/views/searches/index.html.erb
- app/views/shared/_mobile-menu.html.erb
Closes https://www.pivotaltracker.com/story/show/152751422
> Add search placeholder content

- app/assets/javascripts/data_portal.js.erb
- app/assets/javascripts/routers/data_portal.js
- app/assets/javascripts/templates/data_portal/header.jst.ejs
- app/assets/stylesheets/components/shared/c-country-selector.scss
- app/assets/stylesheets/layouts/l-data-portal-country.scss
- app/controllers/data_portal_controller.rb
- app/views/data_portal/show.html.erb
- app/views/data_portal_financial_diaries/_country-selector.html.erb
- app/views/data_portal_financial_diaries/country_preview.html.erb
Tasks: 
https://www.pivotaltracker.com/story/show/153058654
https://www.pivotaltracker.com/story/show/153094263
> breadcrumbs and anchors

- app/views/data_portal/countries/show.html.erb
- app/views/data_portal/index.html.erb
- app/views/data_portal_financial_diaries/countries/show.html.erb
- app/views/data_portal_financial_diaries/country_preview.html.erb
- app/views/data_portal_financial_diaries/index.html.erb
- app/views/homepage/index.html.erb
[Pivotal Task](https://www.pivotaltracker.com/n/projects/1967391/stories/153399046)
> Change finscope name to national surveys

- app/assets/javascripts/pages/data_portal/DataPortalIndexPage.js
- app/assets/stylesheets/layouts/l-data-portal.scss
- app/views/data_portal/index.html.erb
[Pivotal Task](https://www.pivotaltracker.com/n/projects/1967391/stories/153399124)
Clicking the name of the dataset filters the clickable country flags by the selected dataset and scrolls down to the country selection.
@dhakelila Should I add the name of the dataset to the country list (to display selected dataset) even with the scroll after the click on the dataset name?
> Filter data portal country list by dataset

- app/assets/javascripts/pages/data_portal/DataPortalIndexPage.js
- app/views/data_portal/index.html.erb
@dhakelila This is the last change, the option to remove the filtering from the countries.
> Add option to remove dataset filter on countries

- app/controllers/searches_controller.rb
Closes https://www.pivotaltracker.com/story/show/154059960
> Order tags available to filter panel

- app/assets/stylesheets/components/shared/c-hero.scss
> Fix page hero layout

- app/assets/stylesheets/components/shared/c-search.scss
- app/assets/stylesheets/layouts/l-search.scss
- app/views/searches/index.html.erb
Closes https://www.pivotaltracker.com/story/show/154135809
> Differentiate filtered and searched terms and amend search layout

- app/assets/stylesheets/components/about/c-modal-about-read-more.scss
- app/views/static_pages/about.html.erb
Closes https://www.pivotaltracker.com/story/show/154171701
> Update about page copy

- app/controllers/fdapi/household_member_transactions_controller.rb
- app/controllers/fdapi/household_transactions_controller.rb
- app/controllers/fdapi/project_metadata_controller.rb
- app/models/concerns/categorizable.rb
- app/models/household_member_transaction.rb
- app/models/household_member_transaction_history.rb
- app/models/household_transaction.rb
- app/models/household_transaction_history.rb
- app/serializers/household_member_transaction_serializer.rb
- app/serializers/household_transaction_serializer.rb
Reverts Vizzuality/i2i#398
This won't be implemented now in the frontend, so removing it from develop until it's time to merge it.
> Revert "Feature/history value"

- app/javascript/components/fsp-maps/actions.js
- app/javascript/components/fsp-maps/component.js
- app/javascript/components/fsp-maps/index.js
- app/javascript/components/fsp-maps/initial-state.js
- app/javascript/components/fsp-maps/reducers.js
- app/javascript/components/map/component.js
- app/javascript/components/map/controls/basemap/component.js
- app/javascript/components/map/controls/basemap/index.js
- app/javascript/components/map/controls/share/component.js
- app/javascript/components/map/controls/share/index.js
- app/javascript/components/map/controls/share/styles.scss
- app/javascript/components/modal/component.js
- package.json
- yarn.lock
- Save params on url
- Load params from url
- Modal fixes...
> Share control

- app/views/data_portal/index.html.erb
- app/views/homepage/_cover_slider.html.erb
- app/views/homepage/index.html.erb
cherry picking commits from develop as there were some changes that are not approved yet and can not be shown in production.
> Interface changes from Michael

- app/admin/user.rb
- app/assets/stylesheets/layouts/l-account.scss
- app/controllers/users_controller.rb
- app/models/user.rb
- app/views/devise/registrations/new.html.erb
- app/views/users/edit.html.erb
- db/migrate/20190521001411_add_name_surname_institution_position_city_country_attribution_to_users.rb
- db/schema.rb
- Changed styles for user account form.
- Added new attributes to ActiveAdmin.
> Add additional attributes to users

- .gitignore
- app/assets/stylesheets/components/shared/c-card.scss
Data portal card buttons styles fixed
> btn inside cards

- app/assets/javascripts/components/shared/fixed-nav.js
- app/assets/stylesheets/layouts/l-account.scss
- app/views/devise/sessions/new.html.erb
Log in section -> reset password out of password input
> reset link out of login input

- app/assets/stylesheets/components/data-portal/c-flag.scss
- app/assets/stylesheets/components/data-portal/countries-list.scss
- app/assets/stylesheets/components/data-portal/region.scss
- app/views/data_portal/_country.html.erb
- app/views/data_portal/_filtered_country.html.erb
Flag icons styles changed back
Yellow hover added to icons
Shadow added to flags and space between flags modified
> flag icons styles

- app/assets/stylesheets/layouts/shared/l-intro.scss
z-index modified in .l-intro .content
> z-index in intro content

- app/views/data_portal/_filtered_country.html.erb
Flag icons styles modified in geo spatial data
> flag index linked to the rest of flags in data portal

- app/views/geospatial_data/index.html.erb
String to HTML in Data portal / Geospacial Data
> html in string

- CHANGELOG.md
- app/assets/stylesheets/components/data-portal/c-modal-download-all.scss
- app/assets/stylesheets/components/shared/c-modal-attachments.scss
Align checkbox and icon in the download modal form.
Browse to http://localhost:3000/data-portal/BGD/2016 and click on Download all button.
You will see something like this:
[#169335807](https://www.pivotaltracker.com/story/show/169335807)
> align checkbox for download modal

- CHANGELOG.md
- app/assets/javascripts/components/data_portal/modals/modal-download-all.js.erb
- app/assets/javascripts/components/shared/modals/download-more-attachments.js.erb
- app/assets/javascripts/components/shared/modals/download-more-publications.js.erb
- app/assets/javascripts/templates/shared/modals/modal-error-message.jst.ejs
- app/assets/javascripts/templates/shared/modals/modal-success-message.jst.ejs
Added thank you message after the user requests to download.
1. Browse to http://localhost:3000/data-portal/BGD
2. Click on 'Download all' button at the bottom of the page. It will open a download modal.
3. Fill the form and click on "Download"
4. You should see a thank you message
[#166638158](https://www.pivotaltracker.com/story/show/166638158)
> added thank you message to national services

- CHANGELOG.md
- app/models/blog.rb
- app/models/event.rb
- app/models/library.rb
- app/models/news.rb
Fixed an issue where search by iso doesn't return any result.
Search by "ZMB" should return results.
[#169432238](https://www.pivotaltracker.com/story/show/169432238)
> Fixed an issue where search by iso doesn't return any result

- app/javascript/components/sidebar/tabs/component.js
- app/javascript/components/sidebar/tabs/styles.scss
Description of the PR
Only title in sidebar tabs were clickable before. Now the whole tab should be clickable
Go to map and check the whole tab in the sidebar is clickable
https://www.pivotaltracker.com/story/show/169598270
> all tab clickable

- app/assets/javascripts/views/shared/custom-select.js
- app/assets/stylesheets/components/data-portal/c-filters-block.scss
- app/controllers/searches_controller.rb
- app/models/blog.rb
- app/models/event.rb
- app/models/library.rb
- app/models/news.rb
Search functionality.
Just test the search page.
[#169227226](https://www.pivotaltracker.com/story/show/169227226)
> Refactor of search results

- app/javascript/components/map/component.js
Fix adding and removing nearby layers
> Nearby: area and marker done with Leaflet instead of layer manager

- app/javascript/components/fsp-maps/actions.js
- app/javascript/components/fsp-maps/sql/fsp_layer_all.sql
- app/javascript/components/list/component.js
- app/javascript/components/list/styles.scss
- app/javascript/components/map/constants.js
- app/javascript/components/map/legend/component.js
- app/javascript/components/map/legend/legend-item-button-visualizations/component.js
- app/javascript/components/map/legend/legend-item-button-visualizations/legend-item-button-visualizations-tooltip/index.js
- app/javascript/components/sidebar/sectors/component.js
- app/javascript/components/widget/analysis-result/selectors.js
- app/javascript/components/widget/component.js
- app/javascript/components/widget/widget-templates/minimun-distance/component.js
- app/javascript/components/widget/widget-templates/minimun-distance/config.js
- app/javascript/components/widget/widget-templates/number-of-services/component.js
- app/javascript/components/widget/widget-templates/number-of-services/config.js
- app/javascript/components/widget/widget-templates/points-percentage/component.js
- app/javascript/components/widget/widget-templates/points-percentage/config.js
- app/javascript/components/widget/widget-templates/points-percentage/styles.scss
This PR adds a fix for the `all facilities` analysis
> Analysis for all layers fixed

- app/assets/javascripts/routers/data_portal.js
- app/javascript/components/fsp-maps/component.js
This PR solves the fitBounds and the reset of the map when you change between countries
> FSP maps navigation

- CHANGELOG.md
- app/javascript/components/intro/component.js
- app/views/data_portal/fsp_maps/show.html.erb
- package.json
- yarn.lock
Description of the PR
Haiti Logo moved in data portal page
http://localhost:3000/data-portal/HTI/fsp-maps?lat=19.057619267879772&lng=-73.04594999999999&zoom=9
https://www.pivotaltracker.com/story/show/169595013
> Fix: Haiti logo moved

- app/javascript/components/fsp-maps/sql/widgets.sql
- app/javascript/components/intro/components/item/styles.scss
- app/javascript/components/widget/component.js
- app/javascript/components/widget/styles.scss
- app/javascript/components/widget/tooltip/component.js
- app/javascript/components/widget/tooltip/styles.scss
- app/javascript/components/widget/widget-templates/agro-ecological-zones/config.js
- app/javascript/components/widget/widget-templates/minimun-distance/config.js
- app/javascript/components/widget/widget-templates/number-of-services/config.js
- app/javascript/components/widget/widget-templates/points-percentage/config.js
- app/javascript/components/widget/widget-templates/settlement-areas/config.js
- app/javascript/components/widget/widget-templates/sex-percentage/config.js
> sex percentage tooltip

- app/assets/javascripts/components/shared/search.js
- app/assets/javascripts/routers/application.js
⚠️ Before submitting the PR, make sure:
- You are including only one feature
- Commits messages are clear
- You updated the changelog
- You asked someone to review it
---
Description of the PR
What to test? How to do it?
Link to the task(s), if any
> search file moved from static pages to shared folder

- CHANGELOG.md
- app/assets/javascripts/components/shared/modal.js
- app/assets/javascripts/pages/data_portal_financial_diaries/DataPortalFinancialDiariesIndexPage.js
- app/assets/javascripts/templates/shared/modal.jst.ejs
- app/assets/stylesheets/components/shared/c-modal.scss
Description of the PR
New button added as requested to close modal in widgets
https://i2ifacility.org/data-portal/GHA/2010
press save, change, compare or analyse to open modal
https://www.pivotaltracker.com/story/show/145859031
> close btn added to modal
