- app/assets/javascripts/pages/data_portal/DataPortalCountryPage.js
- app/assets/javascripts/views/data_portal/ChartWidgetView.js
This PR takes care of sending the information about the indicators to the filters modal and to re-render the widgets whenever they change.
The filters modal will receive two parameters at instantiation:
- `this.options._indicatorsData` which is the list of indicators with their available options
- `this._onFiltersUpdate` as a callback when the user is done applying filters; it takes as argument the list of applied filters, for example:
```
[
{ name: 'gender', options: ['Female'] },
{ name: 'i2i_Education', options: ['Primary education', 'Secondary education'] }
]
```
means that the user selected `Female`, `Primary education` and `Secondary education` as filters.
Let me know @andresgnlez if that sounds right.
> Load the widgets accordingly to the filters

- app/assets/stylesheets/_settings.scss
- app/assets/stylesheets/components/shared/c-card-highlight.scss
- app/assets/stylesheets/components/shared/c-card.scss
- app/views/data_portal/index.html.erb
- app/views/libraries/index.html.erb
- app/views/updates/events/index.html.erb
- app/views/updates/index.html.erb
- app/views/updates/news/index.html.erb
This PR adjusts the picture card to metadata data content (title and summary) instead of card height  and it was setted before. This way the picture adjust itself better depending on how the metadata content grows.
This change was asked by Dani. There's no Pivotal task related with this.
> Adjusts picture card to content, not card height

- app/controllers/libraries_controller.rb
- app/controllers/updates/blogs_controller.rb
- app/controllers/updates/events_controller.rb
- app/controllers/updates/news_controller.rb
- app/controllers/updates_controller.rb
Pivotal task: https://www.pivotaltracker.com/story/show/141581907
This PR sorts posts/events/news and libraries by update date instead of creation date, like before.
> Sorts posts/news/event/libraries by update date

- app/assets/javascripts/templates/data_portal/chart-tooltip.jst.ejs
- app/assets/javascripts/templates/data_portal/widgets/analysis.jst.ejs
- app/assets/javascripts/templates/data_portal/widgets/bar.jst.ejs
- app/assets/javascripts/templates/data_portal/widgets/pie.jst.ejs
- app/assets/javascripts/templates/data_portal/widgets/radial.jst.ejs
- app/assets/javascripts/views/data_portal/ChartTooltipView.js
- app/assets/javascripts/views/data_portal/ChartWidgetView.js
- app/assets/stylesheets/components/data-portal/c-chart-tooltip.scss
This PR adds tooltips to the charts.
> Implement the charts' tooltip

- app/assets/javascripts/pages/data_portal/DataPortalCountryPage.js
- app/assets/javascripts/templates/data_portal/filters/select-context.jst.ejs
- app/assets/javascripts/views/data_portal/FiltersIndicatorsModal.js
- app/assets/javascripts/views/data_portal/filters/ApplyFiltersView.js
- app/assets/javascripts/views/data_portal/filters/SelectContextView.js
- app/assets/stylesheets/components/data-portal/c-modal-filters.scss
- app/assets/stylesheets/components/shared/c-radio-button.scss
This PR lets the user change the year of a portal. It is part of the new "context" tab of the "customise" modal.
[Pivotal task](https://www.pivotaltracker.com/story/show/141321617)
> Let the user change the year of a portal

- app/assets/javascripts/components/data_portal/modals/modal-chart-compare.js
- app/assets/javascripts/helpers/chartConfig.js
- app/assets/javascripts/helpers/indicators.js
- app/assets/javascripts/helpers/widgetToolbox.js
- app/assets/javascripts/models/data_portal/ChartWidgetModel.js
- app/assets/javascripts/pages/data_portal/DataPortalCountryPage.js
- app/assets/javascripts/templates/data_portal/chart-widget.jst.ejs
- app/assets/javascripts/templates/data_portal/compare/country-year.jst.ejs
- app/assets/javascripts/templates/data_portal/compare/jurisdiction.jst.ejs
- app/assets/javascripts/templates/data_portal/modals/modal-chart-compare.jst.ejs
- app/assets/javascripts/templates/data_portal/widgets/compare.jst.ejs
- app/assets/javascripts/views/data_portal/ChartWidgetView.js
- app/assets/javascripts/views/data_portal/compare/CountryYearView.js
- app/assets/javascripts/views/data_portal/compare/JurisdictionView.js
- app/assets/stylesheets/components/data-portal/c-modal-chart-compare.scss
- app/assets/stylesheets/components/shared/c-checkbox.scss
This PR brings the comparison mode to the indicators. The user as the possibility to compare any strand indicator with the data of the same indicator:
- for other countries and years
- for other jurisdictions
_NOTE: These two options are exclusive._
Within a widget, only three datasets can be compared: the default data of the indicator and two choices made by the user.
The compare mode – as the analysis mode – doesn't let the user change the graph or select another mode at the same time.
> Compare an indicator with other countries/years or other jurisdictions

- app/assets/javascripts/components/data_portal/modals/modal-chart-compare.js
- app/assets/javascripts/models/data_portal/ChartWidgetModel.js
- app/assets/javascripts/pages/data_portal/DataPortalCountryPage.js
- app/assets/javascripts/templates/data_portal/filters/select-context.jst.ejs
- app/assets/javascripts/templates/data_portal/header.jst.ejs
- app/assets/javascripts/templates/data_portal/modals/modal-chart-compare.jst.ejs
- app/assets/javascripts/views/data_portal/ChartWidgetView.js
- app/assets/javascripts/views/data_portal/FiltersIndicatorsModal.js
- app/assets/javascripts/views/data_portal/compare/JurisdictionView.js
- app/assets/javascripts/views/data_portal/filters/SelectContextView.js
This PR adds a new filter to the "context" tab of the "customise" modal: jurisdiction.
NOTE: Once the user has filtered by jurisdiction, the indicators can't be compared with other countries/years.
[Pivotal task](https://www.pivotaltracker.com/story/show/141321355)
> Implement the jurisdiction filter

- app/assets/javascripts/components/shared/tooltip.js
- app/assets/javascripts/templates/data_portal/widget-warning-tooltip.jst.ejs
- app/assets/javascripts/views/data_portal/ChartWidgetView.js
- app/assets/javascripts/views/data_portal/WidgetWarningTooltipView.js
- app/assets/stylesheets/_settings.scss
- app/assets/stylesheets/components/data-portal/c-widget-warning-tooltip.scss
This PR implements a warning tooltip which asks the user to confirm certain actions incompatible with the current state of the widget. Those actions are:
- setting the analysis mode when the compare one is active
- setting the compare mode when the analysis one is active
- changing the chart visualisation when the compare mode is active
- changing the chart visualisation when the analysis mode is active
If the user confirms then the previous mode is disabled and the configuration lost. If they cancel, the tooltip closes.
> Implement a warning tooltip for the widgets

- app/assets/javascripts/components/data_portal/modals/modal-save-widget.js
- app/assets/javascripts/helpers/indicators.js
- app/assets/javascripts/pages/data_portal/DataPortalReportPage.js
- app/assets/javascripts/routers/data_portal.js
- app/assets/javascripts/templates/data_portal/chart-widget.jst.ejs
- app/assets/javascripts/views/data_portal/ChartWidgetView.js
This PR adds a delete button to the widgets of a report. When clicked, the button removes the widget from the report, updates the URL and eventually the local storage.
If the user removes the last widget, they are redirected to the portal's homepage.
> Let the user remove a widget from a report

- app/assets/javascripts/pages/data_portal/DataPortalCountryPage.js
- app/assets/javascripts/views/data_portal/ChartWidgetView.js
- app/assets/javascripts/views/data_portal/SwitcherView.js
- app/assets/stylesheets/components/shared/c-switcher.scss
- app/views/data_portal/show.html.erb
This PR implements the table mode where all the indicators display as tables. While in this mode, the user can still use the filters and add new indicators.
> Implement the table mode

- app/assets/javascripts/views/shared/cards.js
- app/assets/stylesheets/components/shared/c-card.scss
- app/views/initiatives/index.html.erb
- app/views/shared/_cards.html.erb
- app/views/tools/index.html.erb
Closes https://www.pivotaltracker.com/story/show/152234160, https://www.pivotaltracker.com/story/show/152234168, https://www.pivotaltracker.com/story/show/152234176
and towards https://www.pivotaltracker.com/story/show/151636869
**Please note** in addition it appears there is also an issue using Google fonts (https://github.com/desandro/masonry/issues/955). Added to issue: https://www.pivotaltracker.com/story/show/152245386.
> Fix masonry card hero images

- app/assets/stylesheets/components/shared/c-header.scss
- app/assets/stylesheets/components/shared/c-nav.scss
Closes https://www.pivotaltracker.com/story/show/152591539
> Prevent nav collapsing for older versions of Safari on tablet

- app/assets/javascripts/views/financial_diaries/VegaChartView.js
Closes: https://www.pivotaltracker.com/story/show/152430406
@davidsingal @aagm this way allows triggering the custom event without regardless the rendering time. Let me know your thoughts, please.
> Adds render callback to charts

- app/assets/javascripts/pages/static_pages/search/filter-modal.js
*Bug:* When clicking tag, from the resulting search page, the filter tags modal does not display the tags on first load:
> Fix search filter tags rendering

- app/admin/dataset.rb
- app/controllers/datasets_controller.rb
- app/javascript/components/datasets/dataset/component.js
- app/javascript/components/datasets/dataset/styles.scss
- app/javascript/components/datasets/sidebar/styles.scss
- app/services/delete_dataset_from_carto.rb
– Remove dataset from carto if its status changes
– Remove user input from dataset form in ActiveAdmin
– Disable dataset edit button if it is published
> Delete data from carto when unpublishing dataset

- CHANGELOG.md
- app/javascript/components/datasets/sidebar/styles.scss
- config/webpack/environment.js
- config/webpacker.yml
- package.json
- yarn.lock
In the new versions os sass-loader they are not including compilation for files. So we have to include `resolve-url-loader` in webpack. 
(more info and documentation)[https://github.com/rails/webpacker/blob/master/docs/css.md#resolve-url-loader]
But it still doesn’t work for me. So, I put the image url in the relative mode.
Run `./bin/webpack-dev-server` and it should compile perfectly.
> fixin assets compilation with webpacker

- app/models/blog.rb
- app/models/event.rb
- app/models/library.rb
- app/models/news.rb
Added support to search by country name, region name, country iso and region iso.
First, you need to assign a country or region to a new, library, event or blog entity.
Then you can search by that country name assigned.
You should see that entity in the search result.
[#168506853](https://www.pivotaltracker.com/story/show/168506853)
> search by country and regions for library

- app/javascript/components/map/index.js
⚠️ Before submitting the PR, make sure:
- You are including only one feature
- Commits messages are clear
- You updated the changelog - _small fix corresponding to another PR_
- You asked someone to review it
---
Fix: max width should depend on analysis not on sidebar.
data-portal / geospatial data / click on any flag
http://localhost:3000/data-portal/IND/fsp-maps?lat=-1.5818302639606454&layers=%5B%7B%22id%22%3A%22Day%20old%20chick%20hatcheries%22%2C%22opacity%22%3A1%2C%22visibility%22%3Atrue%2C%22visualizationType%22%3A%22normal%22%7D%5D&lng=92.90039062500001&zoom=3
select layer, open analysis, create an area
------ missing  -.-
> map width fixed

- CHANGELOG.md
- app/assets/stylesheets/components/shared/c-nav.scss
- app/assets/stylesheets/components/shared/c-search.scss
- app/views/shared/_header.html.erb
Added search and user text for the login and search icons.
Just check there should be a text for login and search icons on the header.
[#168290899](https://www.pivotaltracker.com/story/show/168290899)
> added text User and Search for the login and search icons on the header

- CHANGELOG.md
- app/views/initiatives/filter_index.html.erb
- app/views/initiatives/index.html.erb
- app/views/shared/_header.html.erb
- app/views/shared/_mobile-menu.html.erb
Changed "Initiatives" to "Research themes"
Ensure Initiatives has been changed to Research themes in the header, the title of the section and links in the breadcrumbs.
[#169448816](https://www.pivotaltracker.com/story/show/169448816)
> Iniatives becomes Research themes

- CHANGELOG.md
- app/assets/stylesheets/components/shared/c-card.scss
Changed color and size for tags inside cards for insights
Browse to the insights page and check the tags should have a gray color and should be smaller than before.
[#169482797]https://www.pivotaltracker.com/story/show/169482797()
> cards on gray color and smaller

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/components/shared/c-form.scss
- app/controllers/contacts_controller.rb
- app/controllers/static_pages_controller.rb
- app/mailers/contact_mailer.rb
- app/models/contact.rb
- app/views/layouts/application.html.erb
- app/views/static_pages/_contact_form_messages.js.erb
- app/views/static_pages/about.html.erb
- config/initializers/simple_form.rb
- config/locales/simple_form.en.yml
- config/routes.rb
- lib/templates/erb/scaffold/_form.html.erb
Migrated contact form to simple form gem.
Run `bundle install`.
Add new env variables to `.env` file:
```
RECAPTCHA_SITE_KEY=""
RECAPTCHA_SECRET_KEY=""
```
Browse to about page. The contact form is on the bottom. You now should be able to fill, send and see errors or a success message.
Link to the task(s), if any
> migrated contact form to simple form

- CHANGELOG.md
- app/assets/stylesheets/layouts/l-data-portal-country.scss
Partner logos in data portal displaying weird. 
Go to data portal and check logo in different tabs and countries. E.g. :
https://i2ifacility.org/data-portal/BGD/2016
https://basecamp.com/1756858/projects/16224488/messages/89402302?enlarge=395634553#attachments_for_message_89402302
https://www.pivotaltracker.com/story/show/170571192
> partners logos width

- CHANGELOG.md
- app/assets/stylesheets/_mixins.scss
- app/assets/stylesheets/exported-components/_mixins.scss
- app/assets/stylesheets/layouts/l-data-portal-country.scss
- app/javascript/components/datasets/sidebar/styles.scss
- app/javascript/components/intro/components/item/styles.scss
- app/javascript/components/map/legend/styles.scss
- app/javascript/components/sidebar/menu-item/styles.scss
- app/javascript/components/sidebar/menu-items/styles.scss
- app/javascript/components/sidebar/sectors/styles.scss
- app/javascript/components/sidebar/styles.scss
- app/javascript/components/widget/analysis-result/styles.scss
- app/javascript/components/widget/widget-templates/minimun-distance/styles.scss
No space between title and header buttons in data-portal header. Extra padding added
CSS triangle and arrow imported from _mixins.
http://localhost:3000/data-portal/COD/2014
https://www.pivotaltracker.com/story/show/170598851
> header buttons padding added
